In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set_palette('husl')
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [2]:
bank= pd.read_csv("D:/pa/bank.csv")
bank

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [3]:
bank.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [4]:
bank.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [5]:
x =bank[['age','day','campaign','balance','duration','previous']]
y =bank[['deposit']]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)
print(x)
print(y)

       age  day  campaign  balance  duration  previous
0       59    5         1     2343      1042         0
1       56    5         1       45      1467         0
2       41    5         1     1270      1389         0
3       55    5         1     2476       579         0
4       54    5         2      184       673         0
...    ...  ...       ...      ...       ...       ...
11157   33   20         1        1       257         0
11158   39   16         4      733        83         0
11159   32   19         2       29       156         0
11160   43    8         2        0         9         5
11161   34    9         1        0       628         0

[11162 rows x 6 columns]
      deposit
0         yes
1         yes
2         yes
3         yes
4         yes
...       ...
11157      no
11158      no
11159      no
11160      no
11161      no

[11162 rows x 1 columns]


In [6]:
model = GaussianNB()
model.fit(x_test,y_test)
expected = y_test
predicted = model.predict(x_test)
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

          no       0.70      0.87      0.77      1205
         yes       0.78      0.56      0.65      1028

    accuracy                           0.72      2233
   macro avg       0.74      0.71      0.71      2233
weighted avg       0.73      0.72      0.72      2233

[[1044  161]
 [ 456  572]]


In [7]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

#confusion_matrix=confusion_matrix(y_test,y_pred) #creating confusion matrix 
acc=accuracy_score(y_test,predicted) 

print(confusion_matrix) 
print('Test accuracy:{:.6f}'.format(acc))

<function confusion_matrix at 0x000001A4D29AE4C8>
Test accuracy:0.723690


In [8]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
encoded_values =le.fit_transform(bank.default)
print(encoded_values)
bank['default'] = le.fit_transform(bank.default)
bank

[0 0 0 ... 0 0 0]


age          job  marital  education  default  balance housing loan  \
0       59       admin.  married  secondary        0     2343     yes   no   
1       56       admin.  married  secondary        0       45      no   no   
2       41   technician  married  secondary        0     1270     yes   no   
3       55     services  married  secondary        0     2476     yes   no   
4       54       admin.  married   tertiary        0      184      no   no   
...    ...          ...      ...        ...      ...      ...     ...  ...   
11157   33  blue-collar   single    primary        0        1     yes   no   
11158   39     services  married  secondary        0      733      no   no   
11159   32   technician   single  secondary        0       29      no   no   
11160   43   technician  married  secondary        0        0      no  yes   
11161   34   technician  married  secondary        0        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [9]:
x =bank[['age','day','campaign','balance','pdays','duration','previous','default']]
y =bank[['deposit']]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)
print(x)
print(y)

       age  day  campaign  balance  pdays  duration  previous  default
0       59    5         1     2343     -1      1042         0        0
1       56    5         1       45     -1      1467         0        0
2       41    5         1     1270     -1      1389         0        0
3       55    5         1     2476     -1       579         0        0
4       54    5         2      184     -1       673         0        0
...    ...  ...       ...      ...    ...       ...       ...      ...
11157   33   20         1        1     -1       257         0        0
11158   39   16         4      733     -1        83         0        0
11159   32   19         2       29     -1       156         0        0
11160   43    8         2        0    172         9         5        0
11161   34    9         1        0     -1       628         0        0

[11162 rows x 8 columns]
      deposit
0         yes
1         yes
2         yes
3         yes
4         yes
...       ...
11157      no
11158     

In [10]:
model = GaussianNB()
model.fit(x_test,y_test)
expected = y_test
predicted = model.predict(x_test)
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

          no       0.72      0.81      0.76      1205
         yes       0.73      0.63      0.68      1028

    accuracy                           0.72      2233
   macro avg       0.73      0.72      0.72      2233
weighted avg       0.73      0.72      0.72      2233

[[972 233]
 [382 646]]


C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

#confusion_matrix=confusion_matrix(y_test,y_pred) #creating confusion matrix 
acc=accuracy_score(y_test,predicted) 

print(confusion_matrix) 
print('Test accuracy:{:.6f}'.format(acc))

<function confusion_matrix at 0x000001A4D29AE4C8>
Test accuracy:0.724586
